### ISSUE TITLE
lesson 4 error

### ISSUE THREAD

**Issue by munkh-altai** [joemaddalone/egghead-flux-architecture#2]
console: Uncaught ReferenceError: _cartItems is not defined

i am tired try fix this error in video. after i was check your git on lesson 4. and i clone your lesson 4's git error same. how to fix this error

**Comment by joemaddalone** [comment]
Good catch!  This has been resolved, just pull down the latest.

**Comment by munkh-altai** [comment]
Thank you @joemaddalone . Good luck
