### ISSUE TITLE
Uncaught Error: Cannot find module "app-catalogitem"

### ISSUE THREAD

**Issue by DimiMikadze** [joemaddalone/egghead-flux-architecture#3]
you have error in app-catalog.js on 4 line.

change 

import CatalogItem from 'app-catalogitem'; 

to 

import CatalogItem from './app-catalogitem';

**Comment by joemaddalone** [comment]
Hunting for it... which branch are you seeing this on?

**Comment by DimiMikadze** [comment]
i guess master, but i don't know exactly:

after cloning repo https://github.com/joemaddalone/egghead-flux-architecture.git, was that error.

**Comment by joemaddalone** [comment]
That line could use a tweak - but should not be causing an error.
`import CatalogItem from '../catalog/app-catalogitem';`
What is the error message you are seeing, exactly?

**Comment by DimiMikadze** [comment]
after cloning the repo and npm start there was error:

Uncaught Error: Cannot find module "app-catalogitem"

[WDS] Errors while compiling.

./src/js/components/catalog/app-catalog.js ...

The problem was in app-catalog.js on 4 line, there was written: 

import CatalogItem from 'app-catalogitem';

after changing to 

import CatalogItem from './app-catalogitem';

error gone.

**Comment by joemaddalone** [comment]
Strange - that's not what the line reads in master.
https://github.com/joemaddalone/egghead-flux-architecture/blob/master/src/js/components/catalog/app-catalog.js

**Comment by DimiMikadze** [comment]
yeas, i checked that.

I'm sorry for confusing maybe i cloned from another branch
